FEAT(Redirect): add 301 redirect manager
bm-sms/daimon-news-multi-tenant pull request #631
Opened 2016-10-04 06:35 UTC by xmeta

Connect to https://github.com/bm-sms/nursepress/issues/311

2016-10-04 06:39 UTC, tricknotes requested changes
そもそもの仕組みと、モデル周りで気になったところにコメントつけました！

2016-10-04 06:39 UTC, tricknotes commented on config/routes.rb
> +  Site.all.each do |site|
リダイレクトルールが設定されるたびに routes を読み直すのはちょっとムダが大きいですかね…。
一旦コントローラで受けるのはどうでしょうか？

2016-10-04 06:39 UTC, tricknotes commented on app/models/redirect.rb
> +class Redirect < ActiveRecord::Base
`Redirection` or `RedirectRule` ?

2016-10-04 06:39 UTC, tricknotes commented on db/migrate/20161003075535_create_redirects.rb
> +      t.string :request
`request` だとリクエストオブジェクトと誤認してしまいそうですね…。
`request_path` とかだとやりたいことに近いです？

2016-10-04 06:39 UTC, tricknotes commented on db/migrate/20161003075535_create_redirects.rb
> +      t.references :site, index: true, foreign_key: true, null: false
`add_index [:request, :site_id], unique: true` のインデックスもほしいですかねー？

2016-10-04 06:41 UTC, tricknotes requested changes

2016-10-04 06:41 UTC, tricknotes commented on app/serializers/redirect_serializer.rb
> +class RedirectSerializer < ActiveModel::Serializer
これはどこからも使われていなさそうですー

2016-10-04 06:42 UTC, okkez commented on app/models/redirect.rb
> +      errors.add(:destination, "リダイレクト ループが発生する設定は追加できません") unless redirect.id == id
変なスペースが入ってますね

2016-10-04 06:49 UTC, xmeta commented on config/routes.rb
> +  Site.all.each do |site|
ちょっとよくわかってないんですが、リダイレクトルールが設定されるたびに routes を読み直さないと、設定が反映されないのではないでしょうか？

今だとここで読み直すようにしてます
https://github.com/bm-sms/daimon-news/pull/631/files#diff-5b46a0ff47aef477464babbe06cff993R33

2016-10-04 06:51 UTC, xmeta commented on app/models/redirect.rb
> +class Redirect < ActiveRecord::Base
`RedirectRule` にしますね

2016-10-04 06:52 UTC, tricknotes commented on config/routes.rb
> +  Site.all.each do |site|
あー、いえ、それは分かるんですが、モデルが作成される度に routes を更新すること自体ムダが大きい(し、そもそもマルチプロセスや複数 dyno の環境で意図したとおりに更新されない)ので避けたいです。

わたしも考え直してみたところ、コントローラだとリダイレクトルールにマッチしなかった場合のフォールバックができないんですね…。
routes より前に評価される必要がありそうなので、 Rack ミドルウェアを作るのだとどうでしょうか？

2016-10-04 06:53 UTC, tricknotes commented on app/models/redirect.rb
> +class Redirect < ActiveRecord::Base
🆒

2016-10-04 06:55 UTC, xmeta commented on config/routes.rb
> +  Site.all.each do |site|
やってみます 😄

2016-10-04 06:55 UTC, tricknotes commented on config/routes.rb
> +  Site.all.each do |site|
さすがです！

2016-10-04 06:57 UTC, tricknotes commented on config/routes.rb
> +  Site.all.each do |site|
Rack ミドルウェアの雰囲気はこんな感じの実装になるんじゃないかなと考えてますー https://github.com/vigetlabs/redirector/blob/v1.0.1/lib/redirector/engine.rb#L6

2016-10-06 01:17 UTC, xmeta commented on config/routes.rb
> +  Site.all.each do |site|
- リクエストがあるたびにrackミドルウェアを通す（RedirectRule.find_byをする）
- リダイレクトルールが設定されるたびに routesを読み直す

のは前者の方がパフォーマンス落ちそうなきがするんですが実際はどうなんだろう・・・
リダイレクトルールの更新頻度によるかなぁ

2016-10-06 01:26 UTC, tricknotes commented on config/routes.rb
> +  Site.all.each do |site|
比較すると前者の方がパフォーマンスはお落ちると思います(SQL 発行することになるので…)
が、まぁ全体の処理時間に比べれば無視できる程度の劣化なんじゃないでしょうか。

(そういえば、後者の方はそもそもマルチテナントを考慮できていないような…)

2016-10-06 01:28 UTC, tricknotes commented on config/routes.rb
> +  Site.all.each do |site|
まぁパフォーマンスが問題になるようなら rack ミドルウェアの方の内部実装を工夫する(RedirectRule の変更を検知してインデックスを構築する or Redis など処理時間の短い KVS を利用する、などなど)余地があるので、仕組みとしてムリがない方法を採用しておいたほうが無難に感じます。

2016-10-06 01:47 UTC, xmeta commented on config/routes.rb
> +  Site.all.each do |site|
> (そういえば、後者の方はそもそもマルチテナントを考慮できていないような…)

でした 🙀

2016-10-06 04:37 UTC, tricknotes commented on config/application.rb
> +    require "#{Rails.root}/lib/redirector"
`require` しちゃうと、rails server 起動中はソースコードを変更しても更新されないので、 autoload_paths に追加するのがよいかとー

2016-10-06 04:38 UTC, tricknotes requested changes

2016-10-06 04:38 UTC, tricknotes commented on db/migrate/20161003075535_create_redirect_rules.rb
> +      t.string :request_path
`null: false`

2016-10-06 04:38 UTC, tricknotes commented on db/migrate/20161003075535_create_redirect_rules.rb
> +      t.string :destination
`null: false`

2016-10-06 04:39 UTC, tricknotes commented on app/models/redirect_rule.rb
> +  def after_change
もういらないですかねー？

2016-10-06 04:42 UTC, tricknotes requested changes

2016-10-06 04:42 UTC, tricknotes commented on lib/redirector.rb
> +      site = Site.find_by(fqdn: request_host)
`Site.find_by(fqdn: request_host)` が引けない状況って、けっこう異常事態だと思うので `find_by!` にしておいたほうがよいかと思います

2016-10-06 04:42 UTC, tricknotes commented on lib/redirector.rb
> +      RedirectRule.find_by(site_id: site.id, request_path: request_path) if site.present?
`site.redirect_rules.find_by`

2016-10-06 04:52 UTC, tricknotes requested changes

2016-10-06 04:52 UTC, tricknotes commented on app/models/redirect_rule.rb
> +    errors.add(:request_path, "/ から始まる相対パスのみ設定できます") unless request_path =~ %r{^/(?!/).*}
`//` は許容しないんですね。(これ自体は問題なさそう)
ただそうするとエラーメッセージが適切ではないような…？

他にも `/a//a` とかも登録できちゃうけど validation かけます？みたいなケースはたくさんありそうなので、いっそ割り切って `request_path.start_with?('/')` の判定だけでよいかなと思いました。
(ユーザの想定を裏切らないような挙動にするためです)

2016-10-06 04:54 UTC, tricknotes commented on app/models/redirect_rule.rb
> +  def after_change
もういらないですかねー？

2016-10-06 04:54 UTC, tricknotes commented on app/models/redirect_rule.rb
> +  def after_change
もういらないですかねー？

2016-10-06 04:59 UTC, tricknotes commented on app/models/redirect_rule.rb
> +    errors.add(:request_path, "クエリパラメーターは含めることができません") if uri.query.present?
エラーメッセージは `config/locales/ja.yml` に定義しておいてくださいなー

2016-10-06 05:00 UTC, tricknotes commented on app/models/redirect_rule.rb
> +    errors.add(:destination, "リダイレクト元とリダイレクト先は同じにできません") if request_path == destination
`request_path == "/hoi"`, `destination == "http://<daimon-news-host>/hoi"` の場合も NG ですかね。

2016-10-06 05:02 UTC, tricknotes commented on app/models/redirect_rule.rb
> +  def after_change
1対1の循環参照はチェックできてますけど、n個のルールで循環参照になる場合のチェックは難しそうですね…。

2016-10-06 05:03 UTC, tricknotes commented on app/views/editor/redirect_rules/index.html.haml
> +        %td= redirect_rule.request_path
リンクになっているとここで動作確認でできて幸せになれそうですね！

2016-10-06 05:04 UTC, tricknotes commented on app/views/editor/redirect_rules/index.html.haml
> +        %td= link_to 'Destroy', editor_redirect_rule_path(redirect_rule), :method => :delete, :data => { :confirm => 'Are you sure?' }
hash syntax は :method => :delete` :arrow_right: `method: :delete` でお願いしますー(コーディングルール的に)

2016-10-06 05:04 UTC, tricknotes commented on app/views/editor/redirect_rules/show.html.haml
> +%p#notice= notice
必要な情報は全部 index に表示されてそうですが、 show 必要ですか？

2016-10-06 05:04 UTC, tricknotes commented on db/structure.sql
> +CREATE TABLE daimon_news_admin_posts (
What is this?

2016-10-06 05:05 UTC, tricknotes commented on db/structure.sql
> +INSERT INTO schema_migrations (version) VALUES ('20151202081744');
?

2016-10-06 05:06 UTC, tricknotes commented on app/models/redirect_rule.rb
> +
`request_path` にクエリストリング(やフラグメントハッシュ)が含められていると意図通りに動かなそうですー

2016-10-06 05:07 UTC, tricknotes commented on app/controllers/editor/redirect_rules_controller.rb
> +    @redirect_rule = redirect_rules.find(params[:id])
削除したモデルを特に使わないのであれば、もう少しシンプルにできそうです
``` ruby
redirect_rules.destroy(params[:id])
```

2016-10-06 05:10 UTC, tricknotes commented on lib/redirector.rb
> +      rule = redirect_rule.freeze
`freeze` は何のために必要なんでしょうか？

2016-10-06 05:17 UTC, tricknotes commented
`RedirectRule#destination` にマルチバイト文字が含まれる可能性を考慮すると、いくつかの個所で `URI.encode` について思いを馳せないといけなかったりしますかね…？

2016-10-06 05:17 UTC, tricknotes commented
テストは全体が整ってきてから考えますかー。

2016-10-06 08:41 UTC, tricknotes requested changes

2016-10-06 08:41 UTC, tricknotes commented on app/models/redirect_rule.rb
> +      errors.add(:destination, I18n.t(:redirect_loop, scope: [:activerecord, :errors, :models, :redirect_rule])) unless redirect_rule.id == id
`I18n.t` 必要でした？
``` ruby
 errors.add(:destination, :redirect_loop
```
でよいのではないかとー

2016-10-06 08:41 UTC, tricknotes commented on config/application.rb
> +    require "redirector"
autoload されませんでした？

2016-10-06 08:41 UTC, tricknotes commented on app/models/redirect_rule.rb
> +    errors.add(:request_path, I18n.t(key, scope: [:activerecord, :errors, :models, :redirect_rule, :request_path]))
ここも `I18n.t` 必要でしたか？

2016-10-11 04:31 UTC, tricknotes requested changes

2016-10-11 04:31 UTC, tricknotes commented on app/controllers/editor/redirect_rules_controller.rb
> +    params["redirect_rules_attributes"].map do |rule|
`map` ?

2016-10-11 04:31 UTC, tricknotes commented on app/controllers/editor/redirect_rules_controller.rb
> +      rule[1]["request_path"] = URI.decode_www_form_component(rule[1]["request_path"])
`params` を上書きしてしまうと、ユーザに入力を参照する方法がなくなってしまってあとになってハマるのでやめたいですね…。
今回の処理は、 `before_validation` で行うのがよかったりしますか？

2016-10-11 04:31 UTC, tricknotes commented on app/middleware/redirector.rb
> +      URI.decode_www_form_component(env["HTTP_HOST"].split(":").first)
`env["HTTP_HOST"]` に decode が必要な場合ってどういうときなんでしょう？

2016-10-11 04:31 UTC, tricknotes commented on app/middleware/redirector.rb
> +      rule = redirect_rule.freeze
`freeze` はどうして必要なんですか？

2016-10-11 04:31 UTC, tricknotes commented on app/models/redirect_rule.rb
> +require "addressable/uri"
これは bundler が require しているので不要なのでは

2016-10-11 04:31 UTC, tricknotes commented on config/routes.rb
> +    get "redirect_rules", controller: "redirect_rules", action: :edit
独自ルールでルーティングを定義してしまうと、Rails way から逸れてしまって直感的にわかりづらくなってしまいがちですね…。

`resources :redirect_rules, only: %i(edit update)` じゃダメでした？

2016-10-11 04:31 UTC, tricknotes commented on test/integration/editor_test.rb
> +  test "既に追加されているリダイレクト元の場合" do
細かい条件を網羅的にテストしたいのであれば、それを満たすのに十分小さなモジュール単位でテストするのがやりやすいかなと思います。
とすると、validation のテストは model のテストで行うべきでしょうか…？

2016-10-11 04:32 UTC, tricknotes requested changes

2016-10-11 04:32 UTC, tricknotes commented on app/middleware/redirector.rb
> +require_relative "../models/site.rb"
必要でした？

2016-10-11 04:32 UTC, tricknotes commented on app/middleware/redirector.rb
> +require "uri"
Rails 環境であれば require 済みだったりしませんでした？

2016-10-11 06:18 UTC, xmeta commented on app/middleware/redirector.rb
> +      rule = redirect_rule.freeze
イミュータブルにしたかったので 😃

2016-10-11 06:26 UTC, xmeta commented on app/middleware/redirector.rb
> +      URI.decode_www_form_component(env["HTTP_HOST"].split(":").first)
`SimpleIDN.to_unicode(env["HTTP_HOST"].split(":").first)` の間違いでした 😓

2016-10-12 04:13 UTC, tricknotes commented on app/models/site.rb
> +  validate :redirect_loop
サイトの更新時にリダイレクトのチェックって必要なんですか？
わたしには、`RedirectRule` モデル内で完結しておいてほしいチェックのように思えますね…。

2016-10-12 07:15 UTC, tricknotes approved these changes

2016-10-12 07:22 UTC, tricknotes requested changes

2016-10-12 07:22 UTC, tricknotes commented on app/middleware/redirector.rb
> +      rule = redirect_rule.freeze
「ミドルウェアの中ではモデルは更新しない」という意思を表明したかったんですかねー？
であれば、 `redirect_rule` メソッドの中で `freeze` しておくのがよいかと思いますー。
``` ruby
def redirect_rule
  site = Site.find_by!(fqdn: request_host)
  site.redirect_rules.find_by(request_path: request_path)&.freeze
end
```

2016-10-12 07:22 UTC, tricknotes commented on app/models/redirect_rule.rb
> +  belongs_to :site, inverse_of: :redirect_rules
`inverse_of` の指定は特に必要ないのかな…と思ってたんですが必要でした？

2016-10-12 07:22 UTC, tricknotes commented on app/models/redirect_rule.rb
> +  def add_error_request_path(key)
`errors.add(:destination, :redirect_loop)` は private メソッドにしないの？という対象性が気になったので、こちらもメソッドにしなくてよいのかなと思いましたがどうでしょうか…？

2016-10-12 07:22 UTC, tricknotes commented on app/views/editor/redirect_rules/_form.html.haml
> += bootstrap_form_for @site, url: [:editor, :redirect_rules], method: "post" do |f|
ひとつづつ追加/削除するので十分かなと考えていたんですが、まとめて処理したくなるケースがありそうでした？

2016-10-12 07:24 UTC, xmeta commented on app/models/redirect_rule.rb
> +  belongs_to :site, inverse_of: :redirect_rules
必要なかったです 😃

2016-10-12 07:27 UTC, xmeta commented on app/models/redirect_rule.rb
> +  def add_error_request_path(key)
一度しか使ってないので、メソッドにするほどでもないかと思いました 😃

2016-10-12 07:29 UTC, xmeta commented on app/views/editor/redirect_rules/_form.html.haml
> += bootstrap_form_for @site, url: [:editor, :redirect_rules], method: "post" do |f|
一度にリダイレクトを編集したいとの要望があったので、このような実装になりました 😃

2016-10-13 02:47 UTC, xmeta commented on config/routes.rb
> +    get "redirect_rules", controller: "redirect_rules", action: :edit
一度にリダイレクトを編集したいとの要望があったので、このような実装になりました 😃

2016-10-13 07:17 UTC, tricknotes commented
> This branch has conflicts that must be resolved

リベースお願いします！

2016-10-13 07:27 UTC, tricknotes commented on app/models/redirect_rule.rb
> +  belongs_to :site, inverse_of: :redirect_rules
これは残したままにしますか？

2016-10-13 07:35 UTC, tricknotes commented on app/models/redirect_rule.rb
> +  def add_error_request_path(key)
いえ、ここで気になったのは「メソッドの対象性」です。
同じような処理がメソッドになっていたりなってしなかったするのは、コードを読む人にとって迷いを生じさせると思います。
`errors.add(:request_path, key)` 自体あえてメソッドにするメリットは感じないので、展開しちゃってよいんじゃないでしょうか？

2016-10-13 07:36 UTC, tricknotes commented on test/models/redirect_rule_test.rb
> +    @default_locale = I18n.locale
`teadown` で元の状態に戻しますか？

2016-10-13 07:37 UTC, tricknotes commented on test/models/redirect_rule_test.rb
> +  sub_test_case "validation" do
せっかくモデルのテストを書いているので、エラーメッセージも検証しましょう！ 💪

2016-10-13 08:22 UTC, tricknotes commented on app/views/editor/redirect_rules/_form.html.haml
> += bootstrap_form_for @site, url: [:editor, :redirect_rules], method: "post" do |f|
うーん、全部いっぺんに編集できるというのは、ほかの UI との統一感の観点からできればやめたいですね…。
CSV インポートを実装する or 初回の登録は daimon チームが CSV or Excel から取り込むのだとどうでしょうか？

2016-10-13 08:40 UTC, ryota-sasabe commented on app/views/editor/redirect_rules/_form.html.haml
> += bootstrap_form_for @site, url: [:editor, :redirect_rules], method: "post" do |f|
記憶がおぼろげでしたが、9/25 に 3人で話した時は、↓のように話してましたね。ただ理由は忘れてしまった..
- 一括登録 / 一括出力 のインターフェースは今回は設けない（出力は DataClips 使えば一応できる）

ユーザー観点で見ると、一括登録自体はできたほうが便利だとは思うので、ほかの UI との統一感 を揃えるのが、ユーザーの利便性(UX)を上回るほど重要なのかなー？というのがちょっと気になりました。

2016-10-13 08:44 UTC, xmeta commented on app/models/redirect_rule.rb
> +  belongs_to :site, inverse_of: :redirect_rules
すでに消えてます 👍

2016-10-13 08:46 UTC, tricknotes commented on app/views/editor/redirect_rules/_form.html.haml
> += bootstrap_form_for @site, url: [:editor, :redirect_rules], method: "post" do |f|
> 9/25 に 3人で話した時は、↓のように話してましたね

その通りです！あえて四本さんがいまの作りにしてるのって、その後別の場所で何か議論があったのかなと思ったのですがそのあたりはどうなんでしょう？

> ユーザー観点で見ると、一括登録自体はできたほうが便利だとは思う

これはユースケースによると思います。たまたま今回必要となっている方が一括で設定したい気持ちが強いんじゃないかなというのがわたしの感想です。
わたしがひとつづつの方がいいと思う一番の理由は、件数の増加に比例してアプリケーション負荷と複雑さが増加する点ですかねぇ…。

2016-10-13 08:47 UTC, xmeta commented on app/views/editor/redirect_rules/_form.html.haml
> += bootstrap_form_for @site, url: [:editor, :redirect_rules], method: "post" do |f|
集客するわけでもないのでUIよりはUXをとった方がいいのかなと思いました

2016-10-13 08:50 UTC, tricknotes commented on app/views/editor/redirect_rules/_form.html.haml
> += bootstrap_form_for @site, url: [:editor, :redirect_rules], method: "post" do |f|
> 集客するわけでもないのでUIよりはUXをとった方がいいのかなと思いました

daimon-news はあくまで共通基盤なので、全体の整合性を考えながら OK/NG の判断を行いたいと考えています。
この PR のコードだと、例えば10000件のリダイレクトルールが登録されていた状態でも快適に利用できますか？

2016-10-13 08:53 UTC, tricknotes commented on app/models/redirect_rule.rb
> +  belongs_to :site, inverse_of: :redirect_rules
4598c2e1f95933301d94278a34b2814126a5692e で確認しましたが、`inverse_of` が残っているように見えるんですが、わたしの確認している場所が間違っていたりしますかね…？

2016-10-13 08:55 UTC, xmeta commented on app/models/redirect_rule.rb
> +  belongs_to :site, inverse_of: :redirect_rules
こちらがが見てるところ間違えてました 😅

2016-10-13 09:14 UTC, ryota-sasabe commented on app/views/editor/redirect_rules/_form.html.haml
> += bootstrap_form_for @site, url: [:editor, :redirect_rules], method: "post" do |f|
一括登録できるという UX を実現するのに、今の UI 以外でも実現できる方法はいろいろありそうだなぁという印象はありますね（現状だと毎回全更新になるように見えますので）。
- 一括登録の専用の画面は切り出して別で用意する
- 一括編集は、一覧から編集したいものを複数選択して、一括編集画面に別に遷移させてそこで対象レコードのみを編集する

とか・・（文章だとイメージしづらい）

> たまたま今回必要となっている方が一括で設定したい気持ちが強い

この UX 自体がそこまで重要かというと確かにそんな気はしますが・・

2016-10-13 09:17 UTC, tricknotes commented on app/views/editor/redirect_rules/_form.html.haml
> += bootstrap_form_for @site, url: [:editor, :redirect_rules], method: "post" do |f|
> 今の UI 以外でも実現できる方法はいろいろありそうだなぁという印象はありますね

ですです！これらの例もよくわかります！まさにそんな感じでもまとめて更新は実現できそうですね！

9/25 に話したときは、「ひとまず一番小さい状態でなるはやでリリースできることを目指しましょうか」というお話をしたので、一つ一つ登録するという案を採用したと記憶してます(リリースされないと、本番で使えないので。。。)

で、もし使い勝手があまりにも悪いということであればこういったまとめて更新する UI を追加で実装するのがいいかなと思います。

2016-10-13 09:32 UTC, xmeta commented on app/views/editor/redirect_rules/_form.html.haml
> += bootstrap_form_for @site, url: [:editor, :redirect_rules], method: "post" do |f|
10000件のリダイレクトを管理するのは大変ですね、そういうニーズが多いならCSVインポートを実装するのが良さそうですね(エクセル等で管理すると思うので)
今の実装は数百件程度を管理するくらいを想定してます・・・

> daimon-news はあくまで共通基盤なので、全体の整合性を考えながら OK/NG の判断を行いたいと考えています。

ちなみに最終的な判断は tricknotes さんが行うことになっているんでしょうか？

2016-10-13 09:36 UTC, xmeta commented on app/views/editor/redirect_rules/_form.html.haml
> += bootstrap_form_for @site, url: [:editor, :redirect_rules], method: "post" do |f|
> * 一括登録の専用の画面は切り出して別で用意する

これが良さそう 🤔

2016-10-13 10:03 UTC, tricknotes commented on app/views/editor/redirect_rules/_form.html.haml
> += bootstrap_form_for @site, url: [:editor, :redirect_rules], method: "post" do |f|
> 今の実装は数百件程度を管理するくらいを想定してます・・・

繰り返しますが、daimon-news は複数のサイトを管理しているので特定のサイトでの用途だけを想定した作りにはしたくないなと考えています。(= ユーザがある程度自由に使って、特に問題なく動く状態)

> ちなみに最終的な判断は tricknotes さんが行うことになっているんでしょうか？

daimon-news に入れる/入れないの判断は daimon チームです。

2016-10-14 00:11 UTC, ryota-sasabe commented on app/views/editor/redirect_rules/_form.html.haml
> += bootstrap_form_for @site, url: [:editor, :redirect_rules], method: "post" do |f|
test

2016-10-14 00:27 UTC, xmeta commented on app/views/editor/redirect_rules/_form.html.haml
> += bootstrap_form_for @site, url: [:editor, :redirect_rules], method: "post" do |f|
> 繰り返しますが、daimon-news は複数のサイトを管理しているので特定のサイトでの用途だけを想定した作りにはしたくないなと考えています。(= ユーザがある程度自由に使って、特に問題なく動く状態)

想定するデータ量によって設計も異なってくると思いますので前提を決めておきたいのですが

* 想定するデータ量は10000件
* ほかの UI との統一感 を揃える
* 一括で設定したい人は少ないので、そちらを考慮する必要はない

という認識であってますでしょうか？

> daimon-news に入れる/入れないの判断は daimon チームです。
daimon チーム全体で合意できた時点でマージするという認識であってますでしょうか？
それとも、daimon チームに所属する一人が承認すればマージ可能ということでしょうか？

2016-10-14 00:37 UTC, ryota-sasabe commented on app/views/editor/redirect_rules/_form.html.haml
> += bootstrap_form_for @site, url: [:editor, :redirect_rules], method: "post" do |f|
> 想定するデータ量は10000件

daimon-news 自体が、どんなサービスが今後乗ってくるかわからないので、データ量をあらかじめ想定しておくことは難しいような気はしますね。今回の件でいうと、データ量が増えた場合でも破綻しない UI になっていればいいのでは。

> 一括で設定したい人は少ないので、そちらを考慮する必要はない

そもそもでいうと 9/25 に、四本さんと tricknotes さんとの MTG で、「ひとまず一番小さい状態でなるはやでリリースできることを目指しましょうか」というお話をしたので、一つ一つ登録するという案を採用した、はずでした。何を優先するかという話なのかなと。

> daimon チーム全体で合意できた時点でマージするという認識であってますでしょうか？

daimon チームで判断と書いてあるので、チームで合意できたら入れるという認識なのではー
（この質問の意図自体がよくわかってない）

2016-10-14 00:39 UTC, ryota-sasabe commented on app/views/editor/redirect_rules/_form.html.haml
> += bootstrap_form_for @site, url: [:editor, :redirect_rules], method: "post" do |f|
四本さんはどうするのがいいと考えてます？

2016-10-14 01:44 UTC, xmeta commented on app/views/editor/redirect_rules/_form.html.haml
> += bootstrap_form_for @site, url: [:editor, :redirect_rules], method: "post" do |f|
今のところ、以下の方法で対処する予定です

* 初期は開発側でCSVなどのデータをもとにリダイレクトルールを登録する
* UI、UXは記事編集と同じようにする

> daimon チームで判断と書いてあるので、チームで合意できたら入れるという認識なのではー（この質問の意図自体がよくわかってない）

「チームで合意できたらマージ」ということでしたら、最初に全員の意見を聞く必要があるのかなと思ったので、後から合意できずにマージできませんとなると手戻りになるので 😅

2016-10-14 01:50 UTC, tricknotes commented on app/views/editor/redirect_rules/_form.html.haml
> += bootstrap_form_for @site, url: [:editor, :redirect_rules], method: "post" do |f|
この PR に関してはわたしが責任を持って見ているので、手戻りについては心配の必要はありません。(これは daimon チームの意見と受け取ってもらって問題ないです)

> 初期は開発側でCSVなどのデータをもとにリダイレクトルールを登録する

これについてはひとまず考えないことにして、最短でリリースすることを考えて実装を進めていただければと思います。

> UI、UXは記事編集と同じようにする

はい、これでお願いします。

2016-10-14 03:53 UTC, xmeta commented on app/views/editor/redirect_rules/show.html.haml
> +%p#notice= notice
UI、UX統一のためです 😃

2016-10-19 09:09 UTC, ryota-sasabe commented on config/routes.rb
> +  root "welcome#index"
💭  routes.rb に差分がたくさんあるのはなぜだろう..

2016-10-19 09:10 UTC, tricknotes commented on config/routes.rb
> +  root "welcome#index"
`s/'/"/g` したのと、あとはムダな `concern` を取り去った結果です

2016-10-20 02:51 UTC, tricknotes approved these changes

2016-10-20 02:51 UTC, merged