Fix menu class
bm-sms/daimon-news-multi-tenant pull request #649
Opened 2016-10-20 08:33 UTC by tricknotes

Don't conflict with `Category#slug` such as "home" or "press".

2016-10-20 09:04 UTC, okkez approved these changes
LGTM!

2016-10-20 09:05 UTC, mtsmfm requested changes

2016-10-20 09:05 UTC, mtsmfm commented on app/views/application/_categories.html.haml
> +    %li.menu__item{class: "menu__item--category__#{category.slug}", data: {menu_item_state: category.root_of?(current_category) ? 'current' : nil}}
How about "menu__item--category-#{category.slug}" ?
In [BEM](http://getbem.com/naming/), `__` means element.
It should be separated by `-` I think.

2016-10-20 09:05 UTC, tricknotes commented on app/views/application/_categories.html.haml
> +    %li.menu__item{class: "menu__item--category__#{category.slug}", data: {menu_item_state: category.root_of?(current_category) ? 'current' : nil}}
ya-

2016-10-21 04:36 UTC, mtsmfm approved these changes

2016-10-21 04:36 UTC, merged