Resized thumbnail feature
bm-sms/daimon-news-multi-tenant pull request #672
Opened 2016-12-20 02:26 UTC by naofumi-fujii

- enables switch of thumbnail by `Site.resize_thumb[:boolean]`

2016-12-20 02:33 UTC, naofumi-fujii commented
sorry, forgot to add some test
it fails currently... ☔️

2016-12-20 03:44 UTC, naofumi-fujii commented
fixed 🔧

2016-12-20 05:49 UTC, naofumi-fujii commented
cant see ci runnning on this PR... ?

2016-12-20 08:55 UTC, naofumi-fujii commented on db/structure.sql
> +SET idle_in_transaction_session_timeout = 0;
not sure about this change... 😟

2016-12-20 08:58 UTC, tricknotes commented on db/structure.sql
> +SET idle_in_transaction_session_timeout = 0;
Don't mind 😎

2016-12-21 09:13 UTC, naofumi-fujii commented
>had a problem deploying to daimon-news-stg-pr-672

😵

2017-01-13 08:57 UTC, naofumi-fujii commented
>had a problem deploying to daimon-news-stg-pr-672

anything i can help?

2017-01-13 09:00 UTC, mtsmfm commented on db/migrate/20161220020802_add_column_to_site.rb
> +    add_column :sites, :resize_thumb, :boolean, default: false, null: false
only site?
we'll get higher benefit if it applies for `Post#thumbnail`

2017-01-13 09:02 UTC, mtsmfm commented
It seems that some thing get wrong on running postdeploy script.

Can you run postdeploy script locally?

https://github.com/bm-sms/daimon-news/blob/master/app.json#L61

2017-01-13 09:04 UTC, mtsmfm requested changes

2017-01-13 09:04 UTC, mtsmfm commented on db/migrate/20161220020802_add_column_to_site.rb
> +    add_column :sites, :resize_thumb, :boolean, default: false, null: false
Ah, this column will be not used I think because carrierwave doesn't store path for versions

2017-01-15 08:47 UTC, naofumi-fujii commented on db/migrate/20161220020802_add_column_to_site.rb
> +    add_column :sites, :resize_thumb, :boolean, default: false, null: false
this column was for some kind like on/off settings by site, 
though i changed my mind to remove this and created new PR at #693

2017-01-18 08:27 UTC, naofumi-fujii commented
closing due to 
https://github.com/bm-sms/daimon-news/pull/672#discussion_r96132694

2017-01-18 08:27 UTC, closed without merging